import "./globals.css";
import { Open_Sans  } from 'next/font/google'

//Components
import Navbar from "@/components/Navbar";

const openSans = Open_Sans({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={openSans.className}>
      <body className="">
        <Navbar />
        <main className="flex flex-col my-5 px-72">
          {children}
        </main>
      </body>
    </html>
  );
}
