import "./globals.css";
import { Nunito } from 'next/font/google'

//Components
import Navbar from "@/components/Navbar.jsx";
import Exp from "@/components/Exp";
import Projects from "@/components/Projects";

const nunito = Nunito({
  weight: ['200', '300', '400', '500', '600', '700', '800', '900', '1000',],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${nunito.className} scroll-smooth`}>
      <body className="mx-auto max-w-3xl px-5 flex flex-col"> 
        <Navbar />
        <main className="flex flex-col" >
          {children}
          <Exp />
          <Projects />
        </main>
      </body>
    </html>
  );
}
